# Site settings
title: DigiTech Solutions
description: Your Digital Marketing Partner
baseurl: "/digital-marketing-agency"
url: "https://sandeepkumar-veeramalla.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md
  - SECURITY.md
  - LICENSE

# Default layout
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Sass settings
sass:
  style: compressed
