# Site settings
title: DigiTech Solutions
description: Your Digital Marketing Partner
baseurl: ""
url: "https://sandeepkumar-veeramalla.github.io/digital-marketing-agency"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Include files
include:
  - assets
  - css
  - js
  - images
  - welcome.html
  - index.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md
  - SECURITY.md
  - LICENSE
